language: node_js
node_js:
  - "12"

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  before_install:
    - openssl aes-256-cbc -K $encrypted_38255b476bef_key -iv $encrypted_38255b476bef_iv -in secret.yml.enc -out secret.yml -d
    - ls -lah
  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s ${STAGE_NAME}
    - cd -

environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PRODUCTION}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PRODUCTION}

  - &UAT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_UAT}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_UAT}

  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEVELOPMENT}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}

jobs:
  include:
    # develop branch deploys to the 'dev' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Experiences API"
      if: type = push AND branch = dev
      env:
        - SERVICE_PATH="backend"
        - STAGE_NAME=dev
        - *DEVELOPMENT_ENV

    # uat branch deploys to the 'uat' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Experiences API"
      if: type = push AND branch = test
      env:
        - SERVICE_PATH="backend"
        - STAGE_NAME=uat
        - *UAT_ENV

    # master branch deploys to the 'prod' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Test Experiences API"
      if: type = push AND branch = master
      env:
        - SERVICE_PATH="backend"
        - STAGE_NAME=prod
        - *PRODUCTION_ENV